WINDOW_THEME_FILES = {
    "close-active": "close-active",
    "close-prelight": "close-active",
    "close-inactive": "close-inactive",
    "hide-active": "minimize",
    "hide-inactive": "minimize",
    "hide-prelight": "minimize",
    "maximize-active": "maximize",
    "maximize-inactive": "maximize",
    "maximize-prelight": "maximize",
    "title-1-active": "title",
    "title-1-inactive": "title",
    "title-2-active": "title",
    "title-2-inactive": "title",
    "title-3-active": "title",
    "title-3-inactive": "title",
    "title-4-active": "title",
    "title-4-inactive": "title",
    "title-5-active": "title",
    "title-5-inactive": "title",
    "top-left-active": "corner",
    "top-left-inactive": "corner",
    "top-right-active": "corner",
    "top-right-inactive": "corner"
}
